/*****************************************************************************/

enum block_KRAKEN_SIGNALS
{
  KRAKEN_TERMINATE,
  KRAKEN_RETURN_PRESENT_TIME,
  KRAKEN_SUGGEST_TIME_STEP,
  KRAKEN_SET_TIME_STEP,
  KRAKEN_SOLVE_STEADY_STATE,
  KRAKEN_SOLVE_TIME_STEP,
  KRAKEN_VALIDATE_TIME_STEP,
  KRAKEN_ABORT_TIME_STEP,
  KRAKEN_GIVE_INPUT_FIELD_TEMPLATES,
  KRAKEN_GIVE_OUTPUT_FIELD_TEMPLATES,
  KRAKEN_GIVE_FIELD_DATA,
  KRAKEN_TAKE_FIELD_DATA,
  KRAKEN_N_SIGNALS
};
